name: Deploy via SSH

on:
  schedule:
    - cron: '0 */5 * * *'  # 每 5 小时执行一次
  workflow_dispatch:  # 支持手动执行  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Execute script on server via SSH using password
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            bash -c "$(curl -Ls https://raw.githubusercontent.com/co2f2e/Serv00/main/singbox_install.sh)" -- 9999
